In [1]:
# Import Dataset
# MEdian, Miin , Max ,Mode
# Box Plot

#Basic R Language

In [2]:
"Helo World"
print("Hello World!")

[1] "Helo World"

[1] "Hello World!"


#R Variables


In [3]:
# Remember that variable names are case-sensitive!
name <- "Rayhan CHowdhury"
age <- 23

name
age

[1] "Rayhan CHowdhury"

[1] 23

In [4]:
# Concatenate Elements
city <- "Faridpur"

paste("My Hometown is", city)

# ----------------------------------
text1 <- "R language is"
text2 <- "Shit"

paste(text1, text2)

# ----------------------------------

num1 <- 31
num2 <- 38

num1+num2

# ----------------------------------
var1 <- var2 <- var3 <- "Orange"

# Print variable values
var1
var2
var3

[1] "My Hometown is Faridpur"

[1] "R language is Shit"

[1] 69

[1] "Orange"

[1] "Orange"

[1] "Orange"

In [5]:
num <- 5
text <- "Some text"

num + text #Error in num + text: non-numeric argument to binary operator


ERROR: Error in num + text: non-numeric argument to binary operator


#R Data Types

In [ ]:
# Numerical
x <- 10.5
class(x) #class is for print the class

#integer
x <- 100
class(x)

# complex
x <- 9i + 3
class(x)

# char
x <- "Hello World"
class(x)

# logical
x <- TRUE
class(x)

#R Numbers


##There are three number types in R language
numeric

integer

complex

In [ ]:
# A numerical daya type is the most commontype in R
x <- 10.3
y <- 3
x
y
class(x)
class(y)

In [ ]:
x <- 1000L
y <- 33L   #L = Integer Literal
x
y
class(x)
class(y)

In [ ]:
#complex
x <- 1000i
y <- 3+5i   #i = √(-1) (imaginary unit)
x
y
class(x)
class(y)

#Type Conversion


In [ ]:
x <- 1000L #int
y <- 2 #Numerical
cat("\n")

# Convert int ot numerical
a <- as.numeric(x)
# convert numerical to int
b <- as.integer(y)
cat("\n")

#X and Y  print
class(x)
class(y)

cat("\n")

#converted print
class(a)
class(b)

#Math Functions

In [ ]:
max(5, 10, 15)
min(5, 10, 15)

cat("\n")
sqrt(16) # squre root

cat("\n")
abs(-4.7) #The abs() function returns the absolute (positive) value of a number:

cat("\n")
ceiling(4.3)#কোনো সংখ্যাকে উপরে নিকটতম পূর্ণসংখ্যায় নিয়ে যায়।

cat("\n") #কোনো সংখ্যাকে নিচে নিকটতম পূর্ণসংখ্যায় নিয়ে যায়।
floor(4.4)

#Strings

In [ ]:
str <- 'Hello World'
str
cat('\n')

str2 <- "
gffowwwefweyfwf,
ffhwhwofwifgwrofh,
jffwfhwrofhohwofh
"
cat(str2) #for print the exactly way cat

cat('\n')
str1 <- 'ABCDEFGHIJKLMNOPQUESUVWXYZ'
nchar(str1)  #nchar একটি string-এর কতগুলো character (অক্ষর) আছে তা গণনা করে।

In [ ]:
str1 <- "Hello"
str2 <- "World"

paste(str1, str2)

In [ ]:
str <- "We called the so-called \"Gladiators\" From the Rome"
str
cat('\n')
cat(str)

##Operators

In [ ]:
# <- → Assign
# == → Equal
# != → Not Equal
# > < → Compare
# & → AND
# | → OR
# ! → NOT
# : → Sequence
# %in% → Exists?
# %*% → Matrix Multiply

#If ... Else

In [ ]:
a <- 300
b <- 33
if(b > a){
  print("B is greater then a")
} else{
  print('a is greater then b')
}

In [ ]:
#Nasted if ..else
x <- 41
if(x>10){
  print("above 10")
}
 if(x>20){
  print("and also above 10")
}else{
  print("below 10!")
}

#AND OR Operators

In [ ]:
#and
a <- 100
b <- 22
c <- 300

if(a>b & c>a){
  print('Both conditions are ture')
}else{
  print('Not true')
}
cat('\n')

# OR
a <- 200
b <- 33
c <- 500

if (a > b | a > c) {
  print("At least one of the conditions is true")
}

#While Loop

In [17]:
i <- 1
while(i < 6){
  print(i)
  i<-i +1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [16]:
#Break
i <- 1
while (i < 6) {
  print(i)
  i <- i + 1
  if (i == 4) {
    break
  }
}

[1] 1
[1] 2
[1] 3


In [15]:
# next
i <- 0
while (i < 6) {
  i <- i + 1
  if (i == 3) {
    next
  }
  print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5
[1] 6


#For Loop

In [14]:
for (x in 1:10) {
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [13]:
fruits <- list('apple', 'banana','manggo')
for(x in fruits){
  print(x)
}

[1] "apple"
[1] "banana"
[1] "manggo"


In [12]:
dice <- c(1,2,3,4,5,6)

for (x in dice) {
  print(d)
}

ERROR: Error: object 'd' not found


In [11]:
#Break
fruits <- list("apple", "banana", "cherry","Jackfruits","Berry")

for (x in fruits) {
  if (x == "cherry") {
    break
  }
  print(x)
}

[1] "apple"
[1] "banana"


In [10]:
# NExt
fruits <- list("apple", "banana", "cherry","Jackfruits","Berry")

for (x in fruits) {
  if (x %in% c("banana", "cherry")) { #c() group banay, %in% check kore group er vitore ache kina”
    next
  }
  print(x)
}

[1] "apple"
[1] "Jackfruits"
[1] "Berry"


In [9]:
# NAsted loop
adj <- list("red", "big", "tasty")

fruits <- list("apple", "banana", "cherry")
  for (x in adj) {
    for (y in fruits) {
      print(paste(x, y))
  }
}

[1] "red apple"
[1] "red banana"
[1] "red cherry"
[1] "big apple"
[1] "big banana"
[1] "big cherry"
[1] "tasty apple"
[1] "tasty banana"
[1] "tasty cherry"


#Function

In [8]:
my_function <- function() {
  print("Hello World!")
}

my_function()

[1] "Hello World!"


In [7]:
my_function <- function(fname) {
  paste(fname, "Chowdhury")
}

my_function("Rayhan")
my_function("Nir")

[1] "Rayhan Chowdhury"

[1] "Nir Chowdhury"

In [6]:
my_function <- function(fname, lname) {
  paste(fname, lname)
}

my_function("Rayhan", "Chowdhury")

[1] "Rayhan Chowdhury"

#Data Structures


In [18]:
# Vectors is used to store multiple values ​​of the same data type together.
numbers <- c(10,20,30,40,50,50)
numbers

[1] 10 20 30 40 50 50

In [19]:
numbers[1]
numbers[3]

[1] 10

[1] 30

In [21]:
#Lists are used to keep different data types together.

student <- list(
  "Rayhan",
  23,
  TRUE
)

print(student)
class(student)

[[1]]
[1] "Rayhan"

[[2]]
[1] 23

[[3]]
[1] TRUE



[1] "list"

In [23]:
#Matrix is ​​used to store similar data in Row × Column format.

mat <- matrix(c(1, 2, 3, 4, 5, 6),
              nrow = 2,
              ncol = 3)

print(mat)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [24]:
#Array is the Similar to the Matrix but can have more dimensions than 2D.

arr <- array(1:12,
dim = c(2,3,2)
)

print(arr)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12



In [28]:
#Data Frame is A table-like data structure where the data types of the columns can be different.

students <- data.frame(
  Name = c('Rayhan', 'Chowdhury', 'Nir'),
  Age = c(22,33,55),
  Passed = c(TRUE, FALSE,TRUE),
  Home = c('Faridpur','Dhaka','CTG')
)

print(students)


       Name Age Passed     Home
1    Rayhan  22   TRUE Faridpur
2 Chowdhury  33  FALSE    Dhaka
3       Nir  55   TRUE      CTG


Vector     → Same Type

List       → Different Type

Matrix     → 2D Same Type

Array      → Multi-Dimensional

Data Frame → Table